"""
pdf_report.py — PDF report generation for covered call analysis results.

Generates a formatted multi-page PDF from one or more AnalyseResponse dicts
(as returned by POST /analyse or POST /analyse-watchlist).

Public API:
    generate_pdf(results, title) -> bytes

Usage:
    from pdf_report import generate_pdf

    pdf_bytes = generate_pdf([result_dict])
    st.download_button("Download PDF", data=pdf_bytes,
                       file_name="report.pdf", mime="application/pdf")

Dependencies:
    fpdf2 — added to frontend/requirements.txt
    Pure Python, no system binaries required, works on Render free tier.
"""

from __future__ import annotations

import sys
import types
from datetime import datetime, timezone


def _ensure_fpdf_importable() -> None:
    """Stub out the cryptography Rust extension if it is broken in the
    current environment (e.g. some CI/sandbox environments that have a
    mismatched pyo3 / cffi build).

    On standard Python installs (Render, local venv) this no-ops because
    cryptography imports cleanly and the stubs are never applied.
    """
    try:
        import cryptography.hazmat.bindings._rust  # noqa: F401 — probe only
        return  # all good; nothing to stub
    except BaseException:
        pass

    # Apply minimal stubs so fpdf2 can load (we never use signing features)
    _STUB_MODS = [
        "cryptography",
        "cryptography.hazmat",
        "cryptography.hazmat.primitives",
        "cryptography.hazmat.primitives.serialization",
        "cryptography.hazmat.primitives.serialization.pkcs12",
        "cryptography.hazmat.primitives.hashes",
        "cryptography.hazmat.primitives._serialization",
        "cryptography.hazmat.bindings",
        "cryptography.hazmat.bindings._rust",
        "cryptography.hazmat.bindings._rust.openssl",
        "cryptography.x509",
    ]
    for name in _STUB_MODS:
        if name not in sys.modules:
            sys.modules[name] = types.ModuleType(name)

    sys.modules["cryptography.hazmat.primitives.hashes"].HashAlgorithm = object
    sys.modules[
        "cryptography.hazmat.primitives.serialization.pkcs12"
    ].load_key_and_certificates = lambda *a, **k: (None, None, [])


_ensure_fpdf_importable()

from fpdf import FPDF  # noqa: E402 — must come after the stub call


# ---------------------------------------------------------------------------
# Layout constants
# ---------------------------------------------------------------------------

_BLUE   = (26, 86, 219)     # #1A56DB — brand primary
_NAVY   = (27, 61, 143)     # #1B3D8F
_HEADER = (197, 203, 245)   # #C5CBF5 — table header fill
_LIGHT  = (240, 244, 255)   # alternating row fill
_WHITE  = (255, 255, 255)
_DARK   = (31, 41, 55)      # near-black text

_MARGIN    = 15   # mm left/right margin
_ROW_H     = 7    # mm standard table row height
_HDR_H     = 8    # mm table header row height
_SECTION_H = 6    # mm section heading height


# ---------------------------------------------------------------------------
# FPDF subclass with header / footer
# ---------------------------------------------------------------------------

class _BreezyPDF(FPDF):
    def __init__(self, title: str):
        super().__init__()
        self._title = title
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*_BLUE)
        self.cell(0, 10, "Breezy F&O - Covered Call Analysis", align="L")
        self.set_text_color(*_DARK)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 10, self._title, align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*_BLUE)
        self.line(self.l_margin, self.get_y(),
                  self.w - self.r_margin, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        self.cell(0, 10,
                  f"Generated by Breezy F&O  ·  {ts}  ·  Page {self.page_no()}",
                  align="C")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _inr(v) -> str:
    if v is None:
        return "-"
    return f"Rs.{v:,.2f}"


def _pct(v) -> str:
    if v is None:
        return "-"
    return f"{v:.2f}%"


def _section_heading(pdf: FPDF, text: str) -> None:
    pdf.set_fill_color(*_NAVY)
    pdf.set_text_color(*_WHITE)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, _SECTION_H, f"  {text}", fill=True,
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*_DARK)
    pdf.ln(1)


def _table_header(pdf: FPDF, cols: list[tuple[str, float]]) -> None:
    """Draw a single header row. cols = [(label, width_mm), ...]"""
    pdf.set_fill_color(*_HEADER)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*_NAVY)
    for label, w in cols:
        pdf.cell(w, _HDR_H, label, border=1, fill=True, align="C")
    pdf.ln()
    pdf.set_text_color(*_DARK)


def _table_row(pdf: FPDF, cells: list[tuple[str, float]],
               fill: bool = False) -> None:
    """Draw one data row. cells = [(value, width_mm), ...]"""
    pdf.set_fill_color(*(_LIGHT if fill else _WHITE))
    pdf.set_font("Helvetica", "", 8)
    for val, w in cells:
        pdf.cell(w, _ROW_H, str(val), border=1, fill=fill, align="R")
    pdf.ln()


# ---------------------------------------------------------------------------
# Per-symbol sections
# ---------------------------------------------------------------------------

def _render_symbol(pdf: _BreezyPDF, res: dict) -> None:
    symbol    = res.get("symbol", "—")
    cmp       = res.get("cmp", 0)
    expiry    = res.get("expiry_date", "—")
    dte       = res.get("days_to_expiry", 0)
    lot_size  = res.get("lot_size", 0)
    pos       = res.get("position", {})
    strikes   = res.get("strikes", [])

    # ── Symbol header ────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_BLUE)
    pdf.cell(0, 9, symbol, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*_DARK)

    pdf.set_font("Helvetica", "", 9)
    info = (f"CMP: {_inr(cmp)}   |   Expiry: {expiry}   |   "
            f"DTE: {dte} days   |   Lot size: {lot_size}")
    pdf.cell(0, 5, info, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # ── Position summary ─────────────────────────────────────────────────────
    _section_heading(pdf, "Position")
    cols = [("Lots", 28), ("Shares", 28), ("Cost Basis/Share", 42),
            ("Total Capital", 42), ("Type", 42)]
    _table_header(pdf, cols)
    hold_type = "Already holds" if pos.get("already_holds") else "Buy-write"
    _table_row(pdf, [
        (str(pos.get("lots", "-")),              28),
        (str(pos.get("shares", "-")),            28),
        (_inr(pos.get("cost_basis_per_share")),  42),
        (_inr(pos.get("total_cost")),            42),
        (hold_type,                              42),
    ])
    pdf.ln(3)

    # ── Strike comparison ────────────────────────────────────────────────────
    _section_heading(pdf, "Strike Analysis")
    scols = [
        ("Type",      18), ("Strike Rs",  24), ("Net Prem Rs", 28),
        ("Breakeven", 24), ("Max Profit", 28), ("Yield %",    20),
        ("Ann Yld %", 22), ("Prot %",    18),
    ]
    _table_header(pdf, scols)
    for i, s in enumerate(strikes):
        _table_row(pdf, [
            (s.get("strike_type", "-"),                18),
            (f"Rs.{s.get('strike', 0):,.0f}",          24),
            (_inr(s.get("net_premium_total")),          28),
            (_inr(s.get("breakeven")),                  24),
            (_inr(s.get("max_profit_total")),           28),
            (_pct(s.get("premium_yield_pct")),          20),
            (_pct(s.get("annualised_yield_pct")),       22),
            (_pct(s.get("downside_protection_pct")),    18),
        ], fill=(i % 2 == 1))

    pdf.ln(4)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_pdf(
    results: list[dict],
    title: str = "Covered Call Analysis Report",
) -> bytes:
    """Generate a PDF report from one or more analyse_covered_call result dicts.

    Args:
        results: List of dicts as returned by POST /analyse or
                 POST /analyse-watchlist (the 'result' field of each item).
                 Must contain at least one entry.
        title:   Report title shown in the page header.

    Returns:
        Raw PDF bytes, suitable for st.download_button(data=...).

    Raises:
        ValueError: If results is empty.
    """
    if not results:
        raise ValueError("results must contain at least one analysis result.")

    pdf = _BreezyPDF(title)
    pdf.set_title(title)
    pdf.set_margins(_MARGIN, 15, _MARGIN)

    for i, res in enumerate(results):
        pdf.add_page()
        _render_symbol(pdf, res)

    return bytes(pdf.output())
